using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EndesaEntity.facturacion
{
    public class Fo_Tabla
    {
        public string ccounips { get; set; }
        public int cemptitu { get; set; }
        public long creferen { get; set; }
        public int secfactu { get; set; }
        public string creffact { get; set; }
        public string cfactura { get; set; }
        public DateTime ffactura { get; set; }
        public DateTime ffactdes { get; set; }
        public DateTime ffacthas { get; set; }
        public long vcuovafa { get; set; }
        public long venereac { get; set; }
        public double vcuofifa { get; set; }
        public double ifactura { get; set; }
        public double iva { get; set; }
        public double base_imposible { get; set; }
        public double iimpues2 { get; set; }
        public double iimpues3 { get; set; }
        public double ibaseise { get; set; }
        public double ise { get; set; }
        public double precio_medio { get; set; }
        public string tfactura { get; set; }
        public string tfactura_descripcion { get; set; }
        public string testfact { get; set; }
        public string dapersoc { get; set; }
        public string cnifdnic { get; set; }
        public int tconfac1 { get; set; }
        public double iconfac1 { get; set; }
        public int tconfac2 { get; set; }
        public double iconfac2 { get; set; }
        public int tconfac3 { get; set; }
        public double iconfac3 { get; set; }
        public int tconfac4 { get; set; }
        public double iconfac4 { get; set; }
        public int tconfac5 { get; set; }
        public double iconfac5 { get; set; }
        public int tconfac6 { get; set; }
        public double iconfac6 { get; set; }
        public int tconfac7 { get; set; }
        public double iconfac7 { get; set; }
        public int tconfac8 { get; set; }
        public double iconfac8 { get; set; }
        public int tconfac9 { get; set; }
        public double iconfac9 { get; set; }
        public int tconfa10 { get; set; }
        public double iconfa10 { get; set; }
        public int tconfa11 { get; set; }
        public double iconfa11 { get; set; }
        public int tconfa12 { get; set; }
        public double iconfa12 { get; set; }
        public int tconfa13 { get; set; }
        public double iconfa13 { get; set; }
        public int tconfa14 { get; set; }
        public double iconfa14 { get; set; }
        public int tconfa15 { get; set; }
        public double iconfa15 { get; set; }
        public int tconfa16 { get; set; }
        public double iconfa16 { get; set; }
        public int tconfa17 { get; set; }
        public double iconfa17 { get; set; }
        public int tconfa18 { get; set; }
        public double iconfa18 { get; set; }
        public int tconfa19 { get; set; }
        public double iconfa19 { get; set; }
        public int tconfa20 { get; set; }
        public double iconfa20 { get; set; }
        public string tindgcpy { get; set; }
        public string tmodopta { get; set; }
        public string crefaext { get; set; }
        public string kperfact { get; set; }
        public string motivo_refacturacion { get; set; }
        public string submotivo { get; set; }
        public string tipo_comentario { get; set; }
        public string comentario_refact { get; set; }
        public double vpotcon1 { get; set; }
        public double vpotcon2 { get; set; }
        public double vpotcon3 { get; set; }
        public double vpotcon4 { get; set; }
        public double vpotcon5 { get; set; }
        public double vpotcon6 { get; set; }
        public double vpotmax1 { get; set; }
        public double vpotmax2 { get; set; }
        public double vpotmax3 { get; set; }
        public double vpotmax4 { get; set; }
        public double vpotmax5 { get; set; }
        public double vpotmax6 { get; set; }
        public double vconath1 { get; set; }
        public double vconath2 { get; set; }
        public double vconath3 { get; set; }
        public double vconath4 { get; set; }
        public double vconath5 { get; set; }
        public double vconath6 { get; set; }
        public double vconathp { get; set; }
        public double vconrth1 { get; set; }
        public double vconrth2 { get; set; }
        public double vconrth3 { get; set; }
        public double vconrth4 { get; set; }
        public double vconrth5 { get; set; }
        public double vconrth6 { get; set; }
        public double vconrthp { get; set; }
        public double vexcere1 { get; set; }
        public double vexcere2 { get; set; }
        public double vexcere3 { get; set; }
        public double vexcere4 { get; set; }
        public double vexcere5 { get; set; }
        public double vexcere6 { get; set; }
        public double preciac1 { get; set; }
        public double preciac2 { get; set; }
        public double preciac3 { get; set; }
        public double preciac4 { get; set; }
        public double preciac5 { get; set; }
        public double preciac6 { get; set; }
        public double precipo1 { get; set; }
        public double precipo2 { get; set; }
        public double precipo3 { get; set; }
        public double precipo4 { get; set; }
        public double precipo5 { get; set; }
        public double precipo6 { get; set; }
        public double vexcepo1 { get; set; }
        public double vexcepo2 { get; set; }
        public double vexcepo3 { get; set; }
        public double vexcepo4 { get; set; }
        public double vexcepo5 { get; set; }
        public double vexcepo6 { get; set; }
        public double vpotcall { get; set; }
        public double vpotcalv { get; set; }
        public double vpotcalp { get; set; }
        public double vpotmaxl { get; set; }
        public double vpotmaxv { get; set; }
        public double vpotmaxp { get; set; }
        public double vconsacl { get; set; }
        public double vconsacv { get; set; }
        public double vconsacp { get; set; }
        public double vconsrel { get; set; }
        public double vconsrev { get; set; }
        public double vconsrep { get; set; }
        public double vexcerel { get; set; }
        public double vexcerev { get; set; }
        public double vexcerep { get; set; }
        public double preciab1 { get; set; }
        public double preciab2 { get; set; }
        public double preciab3 { get; set; }
        public double precipb1 { get; set; }
        public double precipb2 { get; set; }
        public double precipb3 { get; set; }
        public double vexcepol { get; set; }
        public double vexcepov { get; set; }
        public double vexcepop { get; set; }
        public string precidhl { get; set; }
        public string precidhv { get; set; }
        public string precidhp { get; set; }
        public string indempre { get; set; }
        public string cupsree { get; set; }
        public string cfactrec { get; set; }
        public int clinneg { get; set; }
        public string ccomauto { get; set; }
        public string cprovinc { get; set; }
        public string csegmerc { get; set; }
        public int numlabor { get; set; }
        public string tiponegocio { get; set; }
        public double supervalle { get; set; }
        public double energ_ponta { get; set; }
        public double horas_ponta { get; set; }
        public double pot_maxima { get; set; }
        public string comentarios { get; set; }

        public string perfil { get; set; }
        public string calendario { get; set; }
        public string tarifa { get; set; }

    }
}
